"""add check_type to Attendance

Revision ID: 3fc8fbe3f134
Revises: 
Create Date: 2025-05-10 16:01:00.840359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fc8fbe3f134'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_type', sa.Enum('SELF', 'ADMIN', name='check_type_enum'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.drop_column('check_type')

    # ### end Alembic commands ###
