"""Added AbnormalEvent and Alert tables

Revision ID: 9767a2b14223
Revises: e43d7f53b155
Create Date: 2025-07-14 22:25:05.306423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9767a2b14223'
down_revision = 'e43d7f53b155'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abnormal_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('box', sa.String(length=255), nullable=False),
    sa.Column('frame_path', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_handled', sa.Boolean(), nullable=True),
    sa.Column('handle_result', sa.String(length=255), nullable=True),
    sa.Column('handled_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.String(length=255), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('person_box', sa.String(length=255), nullable=False),
    sa.Column('frame_path', sa.String(length=255), nullable=True),
    sa.Column('video_clip', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_handled', sa.Boolean(), nullable=True),
    sa.Column('handle_result', sa.String(length=255), nullable=True),
    sa.Column('handled_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alerts')
    op.drop_table('abnormal_events')
    # ### end Alembic commands ###
