"""Allow null for face_encoding in employees

Revision ID: b8e1885364de
Revises: 42a913da39c5
Create Date: 2025-07-11 12:02:22.493236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8e1885364de'
down_revision = '42a913da39c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('face_encoding',
               existing_type=sa.BLOB(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('face_encoding',
               existing_type=sa.BLOB(),
               nullable=False)

    # ### end Alembic commands ###
