"""Add face_encoding to User table

Revision ID: e43d7f53b155
Revises: b8e1885364de
Create Date: 2025-07-11 12:14:58.250422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e43d7f53b155'
down_revision = 'b8e1885364de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('face_encoding', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('face_encoding')

    # ### end Alembic commands ###
